### ISSUE TITLE
stream truncation bug in jetstream test on node v10.4.1

### ISSUE THREAD

**Issue by kzc** [fabiosantoscode/terser#56]
**Bug report or Feature request?**

Travis CI test failure that only appears in node v10.4.1.

Note: The stream truncation bug is either in the `test/jetstream.js` test itself or is a node 10 issue. Terser is correctly reporting a parse error for the truncated JS input.

**Version (complete output of `terser -V`)**

master

**Complete CLI command or `minify()` options used**

```
curl -s https://browserbench.org/JetStream/SimplePayload.js | bin/uglifyjs -mc -b beautify=false,webkit --timings
```
where `bin/uglifyjs` is `terser`.

Travis CI [log](https://travis-ci.org/fabiosantoscode/terser/jobs/392782541#L3865-L3886):
```
uglifyjs SimplePayload.js -mc -b beautify=false,webkit --timings
Parse error at 0:3,33
    {name: "bigfib.cpp", content:"// The Module object: Our interface to the out
                                 ^
ERROR: Unterminated string constant
    at JS_Parse_Error.get (eval at <anonymous> (/home/travis/build/fabiosantoscode/terser/tools/node.js:21:1), <anonymous>:75:23)
    at fatal (/home/travis/build/fabiosantoscode/terser/bin/uglifyjs:306:53)
    at run (/home/travis/build/fabiosantoscode/terser/bin/uglifyjs:245:9)
    at Socket.<anonymous> (/home/travis/build/fabiosantoscode/terser/bin/uglifyjs:181:9)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
/home/travis/build/fabiosantoscode/terser/test/jetstream.js:43
                    if (code) throw new Error("uglifyjs failed with code " + code);
                              ^
Error: uglifyjs failed with code 1
    at ChildProcess.<anonymous> (/home/travis/build/fabiosantoscode/terser/test/jetstream.js:43:37)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
    1) Should pass with options -mc
```
https://github.com/fabiosantoscode/terser/commit/e913d37fb71c453a59cdb846d91eb7e3881cd880#commitcomment-29382800

**Comment by kzc** [comment]
A previous commit ran all Travis CI tests successfully with the same version of node and npm:

https://travis-ci.org/fabiosantoscode/terser/jobs/392383059#L443-L444

I don't see anything that changed in the environment between the run in the top post and this one. Node 10 flakiness?

**Comment by kzc** [comment]
Running the jetstream test locally on node v10.4.1 works correctly. 

Looking at the Travis CI logs from PR #57 I think I see what's going on.

Here's the [file/size/sha1](https://travis-ci.org/fabiosantoscode/terser/jobs/393215025#L5191) in question for a successful node 8 run for `SimplePayload.js`:
```
./tmp/https%3A%2F%2Fbrowserbench.org%2FJetStream%2FSimplePayload.js 3411255 420a6631bfe5e5ffa57146a57fd2f175e5beba23
```

Here's the [file/size/sha1](https://travis-ci.org/fabiosantoscode/terser/jobs/393215026#L4033) in question for a failed node 10 run:
```
./tmp/https%3A%2F%2Fbrowserbench.org%2FJetStream%2FSimplePayload.js 523264 9cc761e5f449de92dbdc729b9146da55b91998d6
```

Notice that the JS file downloaded by the jetstream test with node 10 is truncated and that leads to the "Unterminated string constant" error in the top post. So `terser` is working correctly. Either the jetstream test itself is faulty or something in the node v10.4.1 https or streaming modules is awry.

**Comment by kzc** [comment]
have node 10 skip jetstream test until stream truncation issue resolved: https://github.com/fabiosantoscode/terser/commit/0fd784cceca0eb707234cbb1ea51514f7bced2ed

**Comment by kzc** [comment]
This issue can be reopened later if need be. Failures not in core Terser library.
