### ISSUE TITLE
Support for async generator methods

### ISSUE THREAD

**Issue by puradox** [fabiosantoscode/terser#97]
**Bug report or Feature request?** Feature

**Version (complete output of `terser -V`)**
```
terser 3.8.1
undefined
```

**Complete CLI command or `minify()` options used**
```js
terser test.js
```

**`terser` input**

```js
// test.js

class Foo {
  async* bar() {
    yield await Promise.resolve(42)
  }
}

const foo = new Foo()
for await (const result of foo.bar()) {
  console.log(result)
}
```

**`terser` output or error**
```
Parse error at test.js:4,12
  async* bar() {
            ^
ERROR: generators cannot be async
    at JS_Parse_Error.get (eval at <anonymous> (/usr/local/google/home/sbalana/dev/catapult/common/node_runner/node_runner/node_modules/terser/tools/node.js:21:1), <anonymous>:75:23)
    at fatal (/usr/local/google/home/sbalana/dev/catapult/common/node_runner/node_runner/node_modules/terser/bin/uglifyjs:318:53)
    at run (/usr/local/google/home/sbalana/dev/catapult/common/node_runner/node_runner/node_modules/terser/bin/uglifyjs:257:9)
    at Object.<anonymous> (/usr/local/google/home/sbalana/dev/catapult/common/node_runner/node_runner/node_modules/terser/bin/uglifyjs:185:5)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Function.Module.runMain (module.js:703:10)
undefined
```

**Expected result**
Not to throw a parsing error.

**Comment by kzc** [comment]
This is easy to implement. Please submit a PR.

Search for "generators cannot be async" in `lib/parse.js` and `AST_ConciseMethod` in `lib/output.js` respectively.

Have the PR include these tests in `test/compress/async.js`:

```js
async_generator_function: {
    options = {
        defaults: true,
    }
    input: {
        async function* baz() {
            yield await Promise.resolve(1);
        }
    }
    expect_exact: "async function*baz(){yield await Promise.resolve(1)}"
}

async_generator_class_method: {
    options = {
        defaults: true,
    }
    input: {
        class Foo {
            async* bar() {
                yield await Promise.resolve(2);
            }
        }
    }
    expect_exact: "class Foo{async*bar(){yield await Promise.resolve(2)}}"
}

async_generator_object_literal_method: {
    options = {
        defaults: true,
    }
    input: {
        foo({
            baz: 4,
            async* bar() {
                yield await Promise.resolve(3);
            },
            qux,
        });
    }
    expect_exact: "foo({baz:4,async*bar(){yield await Promise.resolve(3)},qux:qux});"
}
```

AFAIK an arrow function cannot be an async generator, so you're in luck there.

**Comment by kzc** [comment]
Please include this test variation as well:
```js
async_generator_static_class_method: {
    options = {
        defaults: true,
    }
    input: {
        class Foo {
            static async* bar() {
                yield await Promise.resolve(4);
            }
        }
    }
    expect_exact: "class Foo{static async*bar(){yield await Promise.resolve(4)}}"
}
```
